### ISSUE TITLE
Attempting to run command for listing all Google Classrooms

### ISSUE THREAD

**Issue by kasg1** [jay0lee/GAM#1121] opened 2020-03-20 02:55 UTC
Ran the following command:

gam print courses state active,provisioned owneremail > c:\users\yourusername\desktop\classes.csv (and actually changed it to gam print courses state active,provisioned owneremail > c:\classes.csv)

I let it run for over an hour, nd the file remained at a size of 0KB.

* I have upgraded to the latest GAM release from https://git.io/gamreleases and I still have this issue.
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/gam/wiki, but I couldn't find the full command, so I got the previous command as a suggestion from the GSFE Google+ forum.

Expected outcome (what are you trying to do?):  I want a csv file of all the Google Classrooms in our domain

Actual outcome (what errors or bad behavior do you see instead?):  Nothing

**Comment by taers232c** [comment] 2020-03-20 03:18
Did you see lines like this?
Got 100 Courses...
Got 200 Courses...
Got 300 Courses...

Ross
--
ross.scroggs@gmail.com

**Comment by kasg1** [comment] 2020-03-20 03:24
No, I didn’t :-(

**Comment by taers232c** [comment] 2020-03-20 03:36
Is the same folder as your gam executable, make an empty file named debug.gam
> print courses state active,provisioned owneremail > c:\classes.csv
Wait 45 seconds and hit control-c
delete debug.gam
What's in c:\classes.csv? There should be debugging information.

Ross

--
ross.scroggs@gmail.com

**Comment by kasg1** [comment] 2020-03-20 20:15
Sorry, but how do you do that?

**Comment by taers232c** [comment] 2020-03-20 21:08
What do you not know how to do? Create a file?
--
ross.scroggs@gmail.com

**Comment by kasg1** [comment] 2020-03-20 21:17
Yes.. how do I create that file? Use Notepad?

**Comment by taers232c** [comment] 2020-03-20 21:19
Sure, that works.

**Comment by jay0lee** [comment] 2020-03-27 13:09
closing this out as this is not a bug. If you want to discuss further please use the group:

https://groups.google.com/forum/#!forum/google-apps-manager

**Closed by jay0lee** 2020-03-27 13:09 UTC
