### ISSUE TITLE
TaskScheduler to Produce a print users file

### ISSUE THREAD

**Issue by JeffProkop** [jay0lee/GAM#1154] opened 2020-04-07 17:23 UTC
The issue tracker is for reporting product deficiencies. "How do I?" questions should be posted to the discussion forum at https://groups.google.com/group/google-apps-manager. When in doubt, start at the discussion forum and return here only when instructed to do so.

Please confirm the following:
* I have upgraded to the latest GAM release from https://git.io/gamreleases and I still have this issue.
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/gam/wiki

Full steps to reproduce the issue:
1.  I have successfully created multiple update users tasks successfully and are all running on schedule successfully
2. I am getting an 0x2 error when trying to do a task to create a file showing users last login that works when executed within command prompt.  All permissions on the task are identical to the ones that are operating. 
3. Are print users to a csv file something I should be able to perform?

Expected outcome (what are you trying to do?): Produce a file daily with the following user fields:
print users query "isSuspended=False orgUnitPath=/csdnbhs" > AllUsers_HS.csv fields primaryemail,lastname,firstname,org,lastlogintime

Actual outcome (what errors or bad behavior do you see instead?): 0x2 no file created, even when removing query and specifying the path of the file (which I am able to do to get a csv file for update command)

Is PRINT USERS something I can actually do with TaskScheduler or need I try another path to accomplish this.

**Comment by jay0lee** [comment] 2020-04-15 14:33
If this works when you run the command directly but fails when you schedule the task, the issue is almost certainly with your task scheduler and setup, not GAM. Closing this out but feel free to open a discussion in the group for help:

https://groups.google.com/d/forum/google-apps-manager

**Closed by jay0lee** 2020-04-15 14:33 UTC

**Comment by JeffProkop** [comment] 2020-04-15 14:36
Thank you for the reply!!!! I was successful in producing reports via task scheduler. I am now producing the data point Classroom:last_interactioin_time as a field back into our SIS to monitor our students are using google classroom.

Thank you so much. GAM is absolutely amazing!!!! And even more amazing now that I have been automating processes via task scheduler.

Best,

[cid:b211259e-a43a-4779-998d-07e3f18a8671]

________________________________
