### ISSUE TITLE
Make GAM an importable module

### ISSUE THREAD

**Issue by archimedesdev** [jay0lee/GAM#28] opened 2014-12-25 15:53 UTC
Hi,

I was wondering if you'd be willing to make a quick, small addition.  I thought it might be fun to create a wrapper python script to call some GAM functions, but when I went to import GAM into my file, it runs gam independently (and fails my script since no arguments are being passed to GAM from the command line).  Would it be possible to just add:

if __name__ == '__main__':

before your main section:

  # Main
  reload(sys)
  sys.setdefaultencoding(u'UTF-8')

This will keep the main section from being run if someone is importing GAM into another python file, but still run it normally when called on its own.  It's easy to do independently, but figured I'd provide the feedback for your next release.

Thanks!

**Comment by ipeacocks** [comment] 2015-01-14 13:14
I`ve use gam with my python script just as shell command through os lib:

```Python
import os

print datetime.now()
show_users_list = os.popen("~/Dropbox/myscripts/GAM-3.42/gam.py print users lastlogintime suspended").read()
```

Of course it is not true way.

**Comment by jay0lee** [comment] 2016-10-22 00:57
closing as duplicate of #23

**Closed by jay0lee** 2016-10-22 00:57 UTC
