### ISSUE TITLE
--noauth_local_webserver has no effect

### ISSUE THREAD

**Issue by artooro** [jay0lee/GAM#232] opened 2016-07-04 15:46 UTC
When I try to run `gam.py --noauth_local_webserver create oauth create` on a remote server without a browser it comes up with the normal flow.

If I make it `gam.py --noauth_local_webserver yes create oauth create` also does the same thing.

It doesn't seem like that flag does anything anymore. It used to work. So I'm now stuck authorizing this application.

**Comment by jay0lee** [comment] 2016-07-04 16:19
The bug is that GAM ever shows --noauth_local_webserver as an argument. GAM looks for a file named nobrowser.txt in the same folder as gam.exe or gam.py and uses that to determine that it should show a URL instead of trying to open a local browser.

I believe the issue is fixed in 3.65 but if not it will be in the next release. Just ignore the message and create a file called nobrowser.txt

Jay

**Closed by jay0lee** 2016-07-04 16:19 UTC
