### ISSUE TITLE
Legacy version broke on RHEL6 after version 5.02

### ISSUE THREAD

**Issue by rjaffey** [jay0lee/GAM#1195] opened 2020-05-14 22:44 UTC
The issue tracker is for reporting product deficiencies. "How do I?" questions should be posted to the discussion forum at https://groups.google.com/group/google-apps-manager. When in doubt, start at the discussion forum and return here only when instructed to do so.

Please confirm the following:
* I have upgraded to the latest GAM release from https://git.io/gamreleases and I still have this issue.
* I am typing the command as described in the GAM Wiki at https://github.com/jay0lee/gam/wiki

Full steps to reproduce the issue:
1. Install gam "legacy" version 5.03 or above on up to date RHEL 6 system.
2. Run 'gam' without arguments.

Expected outcome (what are you trying to do?):

$ ./gam/gam 
GAM 5.02 - https://git.io/gam
Jay Lee <jay0lee@gmail.com>
Python 3.8.2 64-bit final
google-api-python-client 1.8.0
Linux Rhel 6.10 Santiago x86_64
Path: /home/gappy/tmp/gam

Usage: gam [OPTIONS]...

GAM. Retrieve or set G Suite domain,
user, group and alias settings. Exhaustive list of commands
can be found at: https://github.com/jay0lee/GAM/wiki

Examples:
gam info domain
gam create user jsmith firstname John lastname Smith password secretpass
gam update user jsmith suspended on
gam.exe update group announcements add member jsmith
...

Actual outcome (what errors or bad behavior do you see instead?):

(version 5.03 or higher):

$ ./gam/gam 
Traceback (most recent call last):
  File "gam.py", line 10782, in ProcessGAMCommand
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "gam.py", line 11594, in <module>
  File "gam.py", line 11572, in ProcessGAMCommand
  File "gam.py", line 112, in showUsage
  File "gam.py", line 605, in doGAMVersion
  File "gam.py", line 562, in getOSPlatform
  File "site-packages/distro.py", line 125, in linux_distribution
  File "site-packages/distro.py", line 680, in linux_distribution
  File "site-packages/distro.py", line 698, in id
  File "site-packages/distro.py", line 903, in lsb_release_attr
  File "site-packages/distro.py", line 556, in __get__
  File "site-packages/distro.py", line 1014, in _lsb_release_info
  File "subprocess.py", line 411, in check_output
  File "subprocess.py", line 512, in run
subprocess.CalledProcessError: Command '('lsb_release', '-a')' returned non-zero exit status 1.
[7811] Failed to execute script gam

Same error regardless of argument list.

**Comment by ejochman** [comment] 2020-05-15 02:12
This looks to be a [`distro`](https://github.com/nir0s/distro/releases) issue, not directly related to gam. What's the output of `pip show distro`? What version of `distro` is installed? If `distro` is not v1.5.0, `pip install --upgrade distro` and see if that fixes the issue or changes the output.

**Comment by rjaffey** [comment] 2020-05-16 00:24
No pip on the system in question.  Some commands used with version >= 5.03 appear to work without problems while others yield additional errors that may shed light on the issue.  Here's an example:

(Version 5.09):

GAM-5.09-gprod/gam/gam user <redacted> print sendas todrive
links: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /tmp/_MEIG1ouUR/libz.so.1)
elinks: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /tmp/_MEIG1ouUR/libz.so.1)

Seems versions released after 5.02 want glibc >=2.14 in some cases.  RHEL6 includes glibc = 2.12.  Looks like the legacy build system might have been upgraded between 5.02 and 5.03, no?  Probably not worth worrying about as RHEL 6 is going away in six months.  It appears that "legacy" is a moving target.  Are there minimum requirements/assumptions for "legacy" described anywhere?  Perhaps I missed something obvious.

**Comment by jay0lee** [comment] 2020-05-16 00:53
I can't reproduce any issues on a clean RHEL6 VM (Google Compute Engine image).

Have you tested this on a clean RHEL6 install?

Note that RHEL6 is *really* old. I'd strongly recommend upgrading to a more recent Linux distro, even if it's just a small VM for running GAM.

@ejochman FYI, the compiled GAM binaries have Python embedded directly into them, are frozen and don't include pip.

**Comment by rjaffey** [comment] 2020-05-16 01:00
I haven't tried a clean install without SCL and various other additions.  The system distro and SCL are as up to date as it gets (SCL is stale...). Clearly there's a difference if you can't reproduce the problem.  Can you confirm glibc version is 2.12 on yours?  Otherwise, no worries.  We're upgrading to RHEL8 in the next few months after which this should be a non-issue.  Thanks.

**Comment by jay0lee** [comment] 2020-05-16 01:13
Yes, it's 2.12.

**Comment by jay0lee** [comment] 2020-05-18 12:01
closing this but feel free to report back if you are still seeing issues with the legacy build.

**Closed by jay0lee** 2020-05-18 12:01 UTC
