### ISSUE TITLE
backendError when updating groups

### ISSUE THREAD

**Issue by mhitchco** [jay0lee/GAM#226] opened 2016-06-07 14:57 UTC
When running 'python gam.py update group groupname@domain.com name newgroupname' I receive the following error.
Temp error backendError. Backing off 16 seconds...attempt 5/10
Temp error backendError. Backing off 32 seconds...attempt 6/10
Temp error backendError. Backing off 60 seconds...attempt 7/10
Temp error backendError. Backing off 60 seconds...attempt 8/10
Temp error backendError. Backing off 60 seconds...attempt 9/10
Temp error backendError. Backing off 60 seconds...attempt 10/10
ERROR: 503: A system error has occurred - backendError

I had my Google reseller try the same with identical results.

**Comment by josemdv** [comment] 2016-06-07 15:36
We are having the exactly same issue.
Using GAM, Apps Script, Python library, etc.
Our scripts were working with no issues and suddenly, everything stopped working (update groups info).

Can you please open a ticket here?

https://code.google.com/a/google.com/p/apps-api-issues/issues/list

Thanks,
Jose

**Comment by githubkusi** [comment] 2016-06-08 14:57
Please star this issue: [https://code.google.com/a/google.com/p/apps-api-issues/issues/detail?id=4553](url)

**Comment by alaumn** [comment] 2016-06-08 15:39
I opened 4553. The response was:
Updates:
        Status: WontFix
        Owner: ryanr...@google.com
        Labels: API-Admin

Comment #2 on issue 4553 by ryanr...@google.com: Temp error backendError when trying to update a Google group
https://code.google.com/a/google.com/p/apps-api-issues/issues/detail?id=4553

GAM is not software maintained by Google. It is a third-party application, and as such you should be reporting issues with it to its developer here:

https://github.com/jay0lee/GAM/issues


Should the developer determine that the issue is with one of the Google APIs the app uses, they should report the issue on this tracker, along with the API details we need to diagnose the problem. As it stands, we do not have enough information here to investigate.

**Comment by mlclemen2** [comment] 2016-06-09 15:06
Same issue here.  Got the same response.  I was able to set the attributes via:
https://developers.google.com/admin-sdk/groups-settings/v1/reference/groups/update

I get the same issue when creating a group.  The group gets created, but with the default attributes.  None of the Attributes I specify get set.

**Comment by cdtphenix** [comment] 2016-06-13 10:33
Same issue with me. I can set th attributes via sdk but I use GAM to do large changes in one copy paste (the last as 200 lines)

**Comment by cdtphenix** [comment] 2016-06-13 13:13
Same issue with me. I can set th attributes via sdk but I use GAM to do large changes in one copy paste (the last as 200 lines)

**Comment by cdtphenix** [comment] 2016-06-13 13:13
Same issue with me. I can set th attributes via sdk but I use GAM to do large changes in one copy paste (the last as 200 lines)

**Comment by cdtphenix** [comment] 2016-06-15 15:30
Hello,
It's working now for me.

**Comment by mlclemen2** [comment] 2016-06-15 18:00
Working for me now as well.

**Comment by PaulLomax** [comment] 2016-06-16 14:24
This was a problem for me for two weeks, but started working again today with no action taken.

**Comment by jay0lee** [comment] 2016-10-21 22:32
Closing. This was likely an issue on Google's end.

**Closed by jay0lee** 2016-10-21 22:32 UTC
