### ISSUE TITLE
gam user (username) delegate to (username) fails with ERROR: 1301

### ISSUE THREAD

**Issue by GuruBuckaroo** [jay0lee/GAM#215] opened 2016-04-04 13:43 UTC
I have been using GAM for years with our Google Apps for Non-Profit/Edu. It has been invaluable. However, as of last week, I've been unable to assign delegates. My GAM version is 3.62 for Windows 7 x64.

I enter the command:
gam user username@domain.org delegate to otheruser@domain.org

I get back:
Giving otheruser@domain.org delegate access to username@domain.org (1 of 1)
ERROR: 1301 - Entity otheruser@domain.org Does Not Exist

I specify the full domain name because it is not our original domain we signed up for Google Apps with, but is a valid secondary domain. This has been working for months since our domain name change last year. I've tried with several different accounts, both as delegate and source, and get the same error in all cases.

**Comment by GuruBuckaroo** [comment] 2016-04-04 15:19
Applied 3.65 and got same error. x64 version if that makes a difference.

**Comment by bondurantdt** [comment] 2016-04-04 16:04
Also receiving this error on 3.63

**Comment by stevendiver** [comment] 2016-04-05 13:09
Seeing the same error mentioned above on GAM 3.62, then again after upgrading to GAM 3.65 (for Mac).

**Comment by steveglachan** [comment] 2016-04-14 05:10
Experiencing the same error. 3.65 x64 windows.

**Comment by Maik-Verge** [comment] 2016-04-14 20:05
GAM 3.65 - http://git.io/gam
Python 2.7.11 64-bit final
google-api-python-client 1.5.0

I just went through the account itself and delegated access via the web gui. 

While the account was already delegated I wanted to see if I got the same error.
gam user delegate to second_user > After manually delegating access I got a different error. Error 1300 this time. Entity exists.

I was able to actually gam delete the delegate from cli, but then attempting to gam delegate access again yielded the same error. 

The user in question I'm trying to give delegate access to is currently suspended in our AD system. 

... I don't think these are correlated but I got the 1300 Entity Exists error again after unsuspending the user in AD. That was the very first time I ran the delegate command again after the 1301 error. So did it delegate?... sure enough, logging into said users account shows that delegate access was given. Did the second_user receive delegate access even though it returned a 1301 error? I didn't in the gui prior, so I'm not certain. 

> run delete delegate command
> check webgui allowing for possible latency, and delegate has been removed from webgui
> run the delegate command again... no error whatsoever... dubya tee eff. 

... I'm stumped. I don't feel like I actually did anything to fix that. If your user's gmail account is tied to AD, I guess it wouldn't hurt to check whether or not their AD account is suspended. I could have sworn I'd delegated many gmail accounts who's AD counterparts were suspended before.

**Comment by GuruBuckaroo** [comment] 2016-04-14 20:37
I've had it work and not work since reporting this. It's intermittent. 

Also, regarding disabled AD users: if you're using GADS, the Google Apps account will be suspended for any disabled AD user, and GAM can't do anything to a suspended account. For that matter, GADS won't do anything with a disabled AD account (other than suspending it) - if you change groups or move to a different OU or anything other than enabling the user, GADS ignores the change.

**Comment by jtopoleskiieee** [comment] 2016-05-13 13:24
Just started to see this myself. Was working fine up until last week then nada. While suspensions always caused an issue it looks like even after you unsuspend the account it still has issues seeing the account is unsuspended.

**Comment by jay0lee** [comment] 2016-05-13 13:27
Can anyone still seeing this issue file a support ticket with Google and
then email me the ticket number?

Jay

On Fri, May 13, 2016, 9:24 AM jtopoleskiieee <notifications@github.com>
wrote:

> Just started to see this myself. Was working fine up until last week then
> nada. While suspensions always caused an issue it looks like even after you
> unsuspend the account it still has issues seeing the account is
> unsuspended.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/jay0lee/GAM/issues/215#issuecomment-219041632>
>
-- 

Jay

**Comment by yubbie** [comment] 2016-05-16 20:13
Interestingly enough, I've had 3.65 running happily for some time now, and
seen this discussion and thought 'Gee, never seen that before."  Yesterday
I did a few delegates, and deleted them all after I was done with my work.
Today I tried to delegate something, and with no changes anywhere in the
last 24 hours, I'm getting the ERROR: 1301 - Entity foo Does Not Exist as
well, for anything I've tried to delegate to!

Haven't opened a ticket with support, but if no one else has, I'm willing
to.  I'll have to carefully say "usng the API" and not mention the word
"GAM" or they'll try to bounce the ticket telling me that GAM is not a
supported product (been there, done that.)

**Comment by patelm63** [comment] 2016-05-23 18:29
I'm having same issue. Getting Error:1301 or 1300. Please Help?

**Comment by nytservicenow** [comment] 2016-06-07 21:01
Does anyone have fix for it?

**Comment by PaulLomax** [comment] 2016-06-16 14:25
I'm having this issue

**Comment by juliamonteagudo** [comment] 2016-06-21 14:45
We have been having this issue for a few months now, and its getting more frequent. Often we get 1301 but the account has actually been delegated. As of last week, it seems that when we get 1301 the accounts are more often than not, not actually delegated. Our automation tool is using 3.65 and I am also having this issue on 3.45, makes me think this is a Google not GAM thing. Has anyone had success contacting google? Did they make a backend change impacting all versions of GAM?

**Comment by juliamonteagudo** [comment] 2016-06-22 16:05
All, please call google and add your domain as effected by this issue **google ticket 09604291**.

Not surprisingly, google didn't want to create a ticket for this issue, but lets see what we can do to get them to look into it.

**Comment by Propergood** [comment] 2016-07-01 10:30
+1

Created some delegates yesterday, all good. 

Downgraded our Gapps edition from unlimited to standard, and today  recieving this error. Initially I assumed the downgrade was responsible, but judging by this issue thread.. Not so convinced now.

**Comment by marco135i** [comment] 2016-07-08 17:47
Has anyone come up with a fix? Has Google updated anyone on the opened Google case in regards to this issue?

**Comment by wisnuWiyantoro** [comment] 2016-08-16 10:40
Hi All,..
I'm having same issue. I use GAM 3.65 version. To fix this problem
 - Please check gam info user xxx@yourdomain and make sure "Account suspended" and "Must change password" should show false
 - If show true please use "gam update user" to change suspended and changepassword attribute.
- wait for the propagation 5-10minutes
- try again gam delegation script.

**Comment by mikerintz** [comment] 2016-08-30 16:58
I'm getting the same error on GAM 3.70 for Windows. I had run the delegate command to delegate access between users in two different domains. GAM created an alias for the receiving account, but then returned a 1301.  Subsequent tries to delegate directly to the alias resulted in the same error.  Confirmed that neither account is suspended, or requires a password change through gam info user.

**Comment by sharrist** [comment] 2016-09-08 18:00
So the strange work around I found for this issue is if you delete user via gam then undelete the user, I was able to delegate properly and the issue disappeared.

**Comment by marco135i** [comment] 2016-09-08 18:44
I logged a ticket with Google and they confirmed it's an issue with the
API. They have been working on a fix for about a month now.





Marco Pereira CSS Manager
Direct: (908) 548-5539 | Onix | www.onixnet.com
18519 Detroit Ave, Lakewood, OH 44107
   <https://www.facebook.com/onixnetworkingcorp>
<https://twitter.com/OnixNetworking>
<https://plus.google.com/u/0/b/114257281714910894253/+Onixnet/postsv>
<https://www.linkedin.com/company/146762?trk=tyah&trkInfo=tarId%3A1415891040156%2Ctas%3Aonix%2Cidx%3A1-3-3>
<https://www.youtube.com/channel/UC7VDlGtQmZag8imvezgkt-w>

**Comment by daethnir** [comment] 2016-09-22 20:35
My testing seems to indicate the issue is related to users who were in a suspended state "long enough".  Once you unsuspend it won't work, but eventually (24hr? more? seems variable) it will start working for them.

Have also added to the google ticket and will keep my fingers crossed that they fix this.

**Comment by thatpixguy** [comment] 2016-10-26 06:06
I'm having this issue too. In this case I could jump through some hoops to do the delegation from the users side, but in 99% of cases this wouldn't be an option for me.

I also noticed that the text in the error message changes slightly depending on which user I am delegating *from*:

```
$ ./gam.py user user1@example.com delegate to admin@example.com
Giving admin@anat.org.au delegate access to user1@example.com (1 of 1)
ERROR: 1301 - Entity  Does Not Exist
$ ./gam.py user user2@example.com delegate to admin@example.com
Giving admin@example.com delegate access to user2@example.com (1 of 1)
ERROR: 1301 - Entity admin@example.com Does Not Exist
```

Note the blank "Entitiy [..] Does Not Exist" for the user1 case.
It turns out user1@example.com was an alias which might have been further confusing things. Either way, nonsensical error message is nonsensical.

This is with a quite old GAM 3.62. I'll update if it's likely to help (though the issue is less pressing now).

```
$ ./gam.py version
GAM 3.62 - http://git.io/gam
Jay Lee <jay0lee@gmail.com>
Python 2.7.9 64-bit final
google-api-python-client 1.4.2
Linux-3.16.0-4-amd64-x86_64-with-LinuxMint-2-betsy x86_64

```

**Comment by CARLOSMECK** [comment] 2016-10-28 14:24
This still fails for me, i can see Jay is adding the 3.8 GAM as we speak. I found this in the 'what's new' notes:

> All Email Settings commands now use new Gmail API.

I'll try and see if it works better.

**Comment by juliamonteagudo** [comment] 2016-10-28 14:25
Please let us know!

Julia V. Monteagudo
Google Apps Admin & Executive Support
The New York Times
212.556.1632 (w)
917.324.9169 (m)
julia.monteagudo@nytimes.com

**Comment by CARLOSMECK** [comment] 2016-10-28 14:42
Tested with GAM 3.8 issue still exist. 

> ERROR: Could not create delegation - 400 - <?xml version="1.0" encoding="UTF-8"?>
> <AppsForYourDomainErrors>
>   <error errorCode="1300" invalidInput="test.user@googleapps.com" reason="EntityExists" />
> </AppsForYourDomainErrors>
>

**Comment by jay0lee** [comment] 2016-10-28 14:44
Actually that's a bit of a lie on the part of the release notes. Delegation is the only API calls in the old Email Settings API still not moved over to the Gmail API yet. Google has stated that they will move these over before Email Settings is turned off. For now, GAM 3.8 still calls the old API but uses the newer client libraries to do so.

As soon as delegation is added to the Gmail API, Ross or I will gladly move this over.

**Comment by CARLOSMECK** [comment] 2016-10-28 14:47
I see, thank you Jay for the response.

**Comment by Sciman3** [comment] 2017-01-05 19:56
Kind of a bump of sorts, I went to do a delegation today for the first time in a month or two, and I'm getting this error. I'm running GAM 4.03.

**Comment by marco135i** [comment] 2017-01-05 20:00
I'm still getting complaints from clients having the same issue as well.





[image: Onix Networking]
Marco Pereira Technical Account Manager
Direct: (908) 548-5539 | Onix | www.onixnet.com
18519 Detroit Ave, Lakewood, OH 44107
   <https://www.facebook.com/onixnetworkingcorp>
<https://twitter.com/OnixNetworking>
<https://plus.google.com/u/0/b/114257281714910894253/+Onixnet/postsv>
<https://www.linkedin.com/company/146762?trk=tyah&trkInfo=tarId%3A1415891040156%2Ctas%3Aonix%2Cidx%3A1-3-3>
<https://www.youtube.com/channel/UC7VDlGtQmZag8imvezgkt-w>

**Comment by daparker** [comment] 2017-01-13 17:18
This happens to me whenever I attempt to delegate access to a suspended account.  However, even if I restore the account in Google, all subsequent attempts to delegate it via GAM continue to fail with the 1301 error.  It's like delegation to that account using GAM is permanently broken if I make this mistake even once.

This is the only issue I have ever experienced with GAM, though.  Unfortunately it's a frustrating one.

**Comment by Dreyfuzz** [comment] 2017-01-31 00:26
Any movement on this? Error 1300 today, GAM 4.11.

**Comment by jay0lee** [comment] 2017-01-31 00:29
The error is on Google's side. There's little gam can do to resolve.

**Comment by Dreyfuzz** [comment] 2017-02-02 19:43
Yup, just checking. Thanks for the great work.

**Comment by thatpixguy** [comment] 2017-02-08 01:38
Is there any way us users can ping google to say "me too" so they get an idea of how many people are affected by the bug? If we were to file a report on our own, which API call is actually failing with that error under the hood? (I'm assuming if we just say we get the error in GAM they will immediately pass the buck back).

**Comment by jay0lee** [comment] 2017-02-08 01:48
@thatpixguy best I can recommend is open a support ticket with Google and mention exact error message you are getting from API.

**Comment by peterberkhout** [comment] 2017-02-08 07:18
I receive this error '1301 - Entity xxx Does Not Exist' since this morning. Last time I used it was a couple of weeks ago and all was working fine. Anyone opened a supportticket with Google yet?
I'd love to 'me too' the ticket.

**Comment by juliamonteagudo** [comment] 2017-02-14 14:54
google ticket 09604291.

you can me too on that

Julia V. Monteagudo
Google Apps Admin & Executive Support
The New York Times
212.556.1632 (w)
917.324.9169 (m)
julia.monteagudo@nytimes.com

**Comment by angryjoe** [comment] 2017-03-10 15:05
I am also seeing this error. What a PITA :\

**Comment by pribis** [comment] 2017-04-03 16:05
Still happening, but what I've noticed is that this is predominantly happening on accounts that are a part of a sub-organization and only on new accounts.  I've deleted delegation for old accounts and re-added with no problem.   Anyone else seeing this?

**Comment by angryjoe** [comment] 2017-04-03 16:41
In talking with support, before you can add delegates, the users need to
sign in and accept terms and conditions. Else, you will not be able to
delegate mail.

**Comment by pribis** [comment] 2017-04-03 16:50
Hmmm, ok, didn't know that.  I'm working in G-Suite, so that sort of thing makes administration kind of a pain.   But anyway, I logged the user in and accepted the terms, but it still doesn't work. 

Also, I was able to delegate for another new user that was in the main organization without a problem and they've not logged in yet.  It is a brand new account.  It is only new users in sub orgs that are presenting a problem.

**Comment by pribis** [comment] 2017-04-03 17:41
angryjoe,  after I waited an hour it worked, so I think you may have been correct.  Still don't know why the other one worked though, but that was helpful advice nonetheless. Thanks.

**Comment by angryjoe** [comment] 2017-04-03 17:44
You are welcome sir :)

**Comment by NoSubstitute** [comment] 2017-06-30 08:55
@juliamonteagudo where can I find that ticket?

**Comment by jay0lee** [comment] 2017-12-16 11:58
closing as I've not seen recent reports of this issue. There's also not much to be done from the GAM end here. Google is working to move Gmail delegation to the new Gmail API and that shoud hopefully improve things here.

**Closed by jay0lee** 2017-12-16 11:58 UTC
