### ISSUE TITLE
groups not updating

### ISSUE THREAD

**Issue by dastrixuk** [jay0lee/GAM#173] opened 2016-01-19 08:18 UTC
I have ran the following command and it does seem to have updated the group

gam update group group@domain.com who_can_view_group all_members_can_view

**Comment by jay0lee** [comment] 2016-10-22 00:53
If the command completed without error then the issue is on Google's side, not GAMs. Closing. Feel free to re-open if you can provide full steps to reproduce with latest GAM release.

**Closed by jay0lee** 2016-10-22 00:53 UTC
