### ISSUE TITLE
Remove custom installer, create setup.py

### ISSUE THREAD

**Issue by zingyb** [jay0lee/GAM#1140] opened 2020-03-30 16:18 UTC
Historically, GAM has shipped with a custom installer script. With all of this great work to split up the project into smaller modules, it behooves the project to also include a proper setup.py.

**Comment by jay0lee** [comment] 2020-03-30 16:46
Most GAM admins utilize the custom installer today. It ensures they are getting the latest version of Python, OpenSSL and Python libraries without the admin needing to install and maintain any of the above. In short, the custom installer is not going anywhere.

I'm not opposed to a setup.py / GAM being pip-installable but it has not been high enough priority for me to carry out. PRs always welcomed.

**Comment by zingyb** [comment] 2020-03-30 16:56
The admin should *have* to install their own Python, OpenSSL, and Python libraries. It's not okay for one userspace application to dictate OS versions and just start mucking around with internals like that. Instructions in a readme file of what prerequisites are needed offer a clear advantage by removing this project's responsibilities of the admin's machines and removing custom code. As it stands, there's a very difficult-to-read installation script clocking in at 375 lines - 202 of which are raising bugs in shellcheck.

**Comment by zingyb** [comment] 2020-03-30 17:04
Case in point, install-gam.sh does not set `set -e` or `set -u`, so any error will be ignored. Line 220 has `temp_archive_dir=$(mktemp -d 2>/dev/null || mktemp -d -t 'mytmpdir')`. If at any point that command outputs nothing or an error, then the program will happily move along. The end of the file has `trap "rm -rf $temp_archive_dir" EXIT`, which will rm -rf a potentially unset variable. GAM is now liable for the possibility of wiping out a user's home directory in entirety. This could be easier to maintain and *safer* if it used standard Python packaging rather than going its own road for no gain.

**Comment by jay0lee** [comment] 2020-03-30 18:34
This is actually a dupe of #720. Again, PRs are always welcome.

**Closed by jay0lee** 2020-03-30 18:34 UTC
Labels: enhancement, help wanted
